export const BOOKMODAL_CLOSE = "BOOKMODAL_CLOSE";
export const BOOKMODAL_EXPAND = "BOOKMODAL_EXPAND";
export const LOGINMODAL_CLOSE = "LOGINMODAL_CLOSE";
export const LOGINMODAL_EXPAND = "LOGINMODAL_EXPAND";